### ISSUE TITLE
Setup Travis crons

### ISSUE THREAD

**Issue by machour** [yiisoft/yii-dev-tool#14] opened 2019-02-18 12:09 UTC
As briefly discussed on slack, it's becoming harder and harder to understand build failures in Yii 3 repos, as packages are inter-dependent and a tiny change in A can brake B without us noticing for days.

As a counter measure, could we setup [Travis cronjobs](https://docs.travis-ci.com/user/cron-jobs/) as suggested by @rob006 on all repositories to run like every 2 days? (still unsure about the right periodicity)

**Comment by rugabarbo** [comment] 2019-10-14 08:46
Where will we send notifications?

Travis supports the following options:
* [Slack](https://docs.travis-ci.com/user/notifications/#configuring-slack-notifications)
* [Email](https://docs.travis-ci.com/user/notifications/#configuring-email-notifications)
* [webhooks](https://docs.travis-ci.com/user/notifications/#configuring-webhook-notifications)
* [IRC](https://docs.travis-ci.com/user/notifications/#configuring-irc-notifications)
* [Campfire](https://docs.travis-ci.com/user/notifications/#configuring-campfire-notifications)
* [Flowdock](https://docs.travis-ci.com/user/notifications/#configuring-flowdock-notifications)
* [HipChat](https://docs.travis-ci.com/user/notifications/#configuring-hipchat-notifications)
* [Pushover](https://docs.travis-ci.com/user/notifications/#configuring-pushover-notifications)
* [OpsGenie](https://docs.travis-ci.com/user/notifications/#configuring-opsgenie-notifications)

It seems to me that the best idea for group alerts in our case is **Slack**. Travis documentation has [great example](https://docs.travis-ci.com/user/notifications/#configuring-multiple-notification-targets-with-different-configurations) of separating alerts based on the build result. This allows you to receive notifications of successful builds in one channel, and notifications of failed builds in another:

```yml
notifications:
  slack:
    - rooms:
        - <account>:<token>#failures
      on_success: never
      on_failure: always
      template:
        - "%{repository_slug} (%{commit}) : %{message}"
        - "Build details: %{build_url}"
    - rooms:
        - <account>:<token>#successes
      on_success: always
      on_failure: never
      template:
        - "%{repository_slug} (%{commit}) : %{message}"
        - "Build details: %{build_url}"
```

**Comment by samdark** [comment] 2019-10-14 09:20
Yes, Slack should be fine.

**Comment by rugabarbo** [comment] 2019-10-14 09:36
@samdark can you add two new slack rooms for these purposes? We will invite everyone who is interested in receiving notifications to these rooms.

**Comment by samdark** [comment] 2019-10-14 09:42
Added `build-successes` and `build-failures`.

**Comment by rugabarbo** [comment] 2019-10-14 11:25
@samdark now we need to encrypted credentials for Slack integration, which we can use in public repositories. Set up a [new Travis CI integration](https://docs.travis-ci.com/user/notifications#configuring-slack-notifications) and encrypt the tokens of each room.

I need encrypted credentials for both rooms. Our public configuration will look something like this:
```yml
notifications:
    slack:
        - rooms:
              - secure: "ABC5OwLpwB7L6Ca...."
          on_success: never
          on_failure: always
          template:
              - "%{repository_slug} (%{commit}) : %{message}"
              - "Build details: %{build_url}"
        - rooms:
              - secure: "ABC5OwLpwB7L6Ca...."
          on_success: always
          on_failure: never
          template:
              - "%{repository_slug} (%{commit}) : %{message}"
              - "Build details: %{build_url}"
```

You see here the encrypted string "ABC5OwLpwB7L6Ca....", which I need for adjusting travis configs in yii public repositories.

**Comment by samdark** [comment] 2019-10-14 12:45
> Your workspace has reached the integration limit

:(

**Comment by rugabarbo** [comment] 2019-10-14 14:51
Hmm... 

Do we really need all these apps?
How to understand which of this can be safely disabled? 
What is not used? Is it real to understand?

![19 10 14-17 47 46](https://user-images.githubusercontent.com/6429469/66760468-d6f8ee80-eeaa-11e9-8ff5-8362d5d1b8fd.jpg)

**Comment by samdark** [comment] 2019-10-14 15:54
Oh. Wow. I have no idea why all these are enabled :) Thanks for pointing it.

**Comment by samdark** [comment] 2019-10-14 16:20
Not sure I've got the tokens correctly but it should be so.

**Comment by rugabarbo** [comment] 2019-10-14 17:03
Great :)

Now... for a test we'll take two repositories – one with the last successful build and one with a failed one.
1) https://travis-ci.org/yiisoft/di [![Build Status](https://travis-ci.org/yiisoft/di.svg?branch=master)](https://travis-ci.org/yiisoft/di)
2) https://travis-ci.org/yiisoft/yii-captcha [![Build Status](https://travis-ci.org/yiisoft/yii-captcha.svg?branch=master)](https://travis-ci.org/yiisoft/yii-captcha)

In each I'll create a PR with a configuration of notifications. Next, we'll add Travis cronjobs for them  and make sure that everything works as intended.

**Comment by samdark** [comment] 2019-10-14 17:29
Do you need these merged?

**Comment by rugabarbo** [comment] 2019-10-14 17:30
Yes, merge both PRs to the **master** branch in both repositories.

**Comment by samdark** [comment] 2019-10-14 17:31
Done.

**Comment by rugabarbo** [comment] 2019-10-14 17:35
Now open two pages:
1) https://travis-ci.com/yiisoft/di/settings
2) https://travis-ci.com/yiisoft/yii-captcha/settings

Find "Cron Jobs" section there.

Add the following schedule for both repositories:
![19 10 14-20 34 05](https://user-images.githubusercontent.com/6429469/66771118-0f57f700-eec2-11e9-8f26-2d873ab7d3eb.jpg)

**Comment by samdark** [comment] 2019-10-14 17:39
Scheduled.

**Comment by rugabarbo** [comment] 2019-10-14 17:50
Hmm ... something strange happened. In Travis, the build history for these repositories has disappeared.
1) https://travis-ci.com/yiisoft/di/builds
2) https://travis-ci.com/yiisoft/yii-captcha/builds

I no longer see a single build on these pages :(

**Comment by samdark** [comment] 2019-10-14 17:58
These are at .org (yes, messy): https://travis-ci.org/yiisoft/di/builds

**Comment by samdark** [comment] 2019-10-14 17:59
I've set up there as well.

**Comment by rugabarbo** [comment] 2019-10-14 18:01
Damn, these Travis domains are some kind of hell :) 
Now we will wait for a builds on schedule.

**Comment by samdark** [comment] 2019-10-14 18:05
I'm thinking more and more about CircleCI...

**Comment by rugabarbo** [comment] 2019-10-14 18:33
Two builds ended more than 20 minutes ago:
1. https://travis-ci.org/yiisoft/di/builds/597764297
2. https://travis-ci.org/yiisoft/yii-captcha/builds/597764290

But there are no notifications in Slack... So something went wrong.
I'll try to understand what the problem is.

> I'm thinking more and more about CircleCI...

With the exception of domain confusion, Travis seems to work well :) There are no other objective reasons for changing it...

**Comment by samdark** [comment] 2019-10-14 18:52
Well, https://circleci.com/circleci-versus-travisci/

**Comment by samdark** [comment] 2019-10-14 19:19
![image](https://user-images.githubusercontent.com/47294/66777101-be033400-eed0-11e9-925e-f8bf48e76514.png)

**Comment by rugabarbo** [comment] 2019-10-14 19:21
> Well, https://circleci.com/circleci-versus-travisci/

This is just marketing... We should look at what is really inconvenient for us now in Travis, and not what CircleCI promises in its comparisons :)

**Comment by samdark** [comment] 2019-10-14 19:39
The issue with notifications is likely connected with the fact that encrypted tokens are tied to concrete repository (this one). Repository is specified during the generation process.

**Comment by rugabarbo** [comment] 2019-10-15 12:57
I just programmatically encrypted Slack token **without** using [Travis CI client](https://github.com/travis-ci/travis.rb#the-travis-client-). Then created PR using this token: https://github.com/yiisoft/yii-captcha/pull/23

Build failed: https://travis-ci.org/yiisoft/yii-captcha/builds/598125538
Notification came to Slack:

![image](https://user-images.githubusercontent.com/6429469/66832726-2ac70e80-ef63-11e9-8f93-c9541e5b191d.png)

Thus, the process of generating encrypted tokens for 80 repositories can be automated.

**Comment by samdark** [comment] 2019-10-15 13:00
Is it still per-repository token?

**Comment by rugabarbo** [comment] 2019-10-15 13:04
> Is it still per-repository token?
Yes. It is :) The token can only be generated using the name of the repository.

The process of setting schedules can also be automated: https://developer.travis-ci.com/resource/cron#create

It seems that it’s possible to write a small script that will do everything for us :)

I'll think a little more about it ...

**Comment by rugabarbo** [comment] 2019-10-22 20:38
Guys, for clarity: I’m going to first deal with task #27, and then implement a console command that can generate Travis cronjobs and encrypted Slack tokens for integration.

**Comment by rugabarbo** [comment] 2019-12-03 22:43
@samdark 

1. Merge #57 
2. [Update](https://github.com/yiisoft/yii-dev-tool/#upgrade) `yii-dev-tool` locally 
3. Go to Slack and copy Travis CI **token**
4. Place the token in file `yii-dev-tool/config/travis/slack.local.php` (use `slack.local.php.example` as example)
5. Prepare the repositories for pushing new things
6. Run `./yii-dev travis/update-slack-config --verbose`
7. Push the changes to the repositories

**Comment by samdark** [comment] 2019-12-04 10:43
@rugabarbo done.

**Comment by samdark** [comment] 2019-12-04 11:06
So now we have notifications. What's left if setting up cronjobs.

**Comment by samdark** [comment] 2019-12-04 11:07
Thank you, @rugabarbo.

**Comment by rugabarbo** [comment] 2019-12-05 12:56
I installed a cronjob for all repositories using command `./yii-dev travis/ensure-cronjob` (see PR #58).

I had to install both on **travis-ci.COM** and **travis-ci.ORG**, because it’s not possible to determine exactly which domain each repository is active on 😞 Mess...

**Comment by samdark** [comment] 2019-12-05 14:07
Everything seems to be in place now. Closing.

**Comment by samdark** [comment] 2019-12-05 14:07
Thanks, @rugabarbo

**Comment by rugabarbo** [comment] 2019-12-06 14:31
@samdark reopen, please.

Builds of repositories, which are located only on domain travis-ci.**COM**, are launched by cron, but notifications do not come to Slack... 

We need to think about why this is happening and fix it.

<details>
<summary>See details (carefully, there will be a big table and many pictures):</summary>

Package | travis-ci.COM | travis-ci.ORG | Slack Notification
---|---|---|---
docs | [![Build Status](https://travis-ci.com/yiisoft/docs.svg?branch=master)](https://travis-ci.com/yiisoft/docs) | [![Build Status](https://travis-ci.org/yiisoft/docs.svg?branch=master)](https://travis-ci.org/yiisoft/docs) | 
di | [![Build Status](https://travis-ci.com/yiisoft/di.svg?branch=master)](https://travis-ci.com/yiisoft/di) | [![Build Status](https://travis-ci.org/yiisoft/di.svg?branch=master)](https://travis-ci.org/yiisoft/di) | ✔
injector | [![Build Status](https://travis-ci.com/yiisoft/injector.svg?branch=master)](https://travis-ci.com/yiisoft/injector) | [![Build Status](https://travis-ci.org/yiisoft/injector.svg?branch=master)](https://travis-ci.org/yiisoft/injector) | 
factory | [![Build Status](https://travis-ci.com/yiisoft/factory.svg?branch=master)](https://travis-ci.com/yiisoft/factory) | [![Build Status](https://travis-ci.org/yiisoft/factory.svg?branch=master)](https://travis-ci.org/yiisoft/factory) | 
access | [![Build Status](https://travis-ci.com/yiisoft/access.svg?branch=master)](https://travis-ci.com/yiisoft/access) | [![Build Status](https://travis-ci.org/yiisoft/access.svg?branch=master)](https://travis-ci.org/yiisoft/access) | 
event-dispatcher | [![Build Status](https://travis-ci.com/yiisoft/event-dispatcher.svg?branch=master)](https://travis-ci.com/yiisoft/event-dispatcher) | [![Build Status](https://travis-ci.org/yiisoft/event-dispatcher.svg?branch=master)](https://travis-ci.org/yiisoft/event-dispatcher) | ✔
security | [![Build Status](https://travis-ci.com/yiisoft/security.svg?branch=master)](https://travis-ci.com/yiisoft/security) | [![Build Status](https://travis-ci.org/yiisoft/security.svg?branch=master)](https://travis-ci.org/yiisoft/security) | 
data | [![Build Status](https://travis-ci.com/yiisoft/data.svg?branch=master)](https://travis-ci.com/yiisoft/data) | [![Build Status](https://travis-ci.org/yiisoft/data.svg?branch=master)](https://travis-ci.org/yiisoft/data) | 
profiler | [![Build Status](https://travis-ci.com/yiisoft/profiler.svg?branch=master)](https://travis-ci.com/yiisoft/profiler) | [![Build Status](https://travis-ci.org/yiisoft/profiler.svg?branch=master)](https://travis-ci.org/yiisoft/profiler) | 
aliases | [![Build Status](https://travis-ci.com/yiisoft/aliases.svg?branch=master)](https://travis-ci.com/yiisoft/aliases) | [![Build Status](https://travis-ci.org/yiisoft/aliases.svg?branch=master)](https://travis-ci.org/yiisoft/aliases) | 
serializer | [![Build Status](https://travis-ci.com/yiisoft/serializer.svg?branch=master)](https://travis-ci.com/yiisoft/serializer) | [![Build Status](https://travis-ci.org/yiisoft/serializer.svg?branch=master)](https://travis-ci.org/yiisoft/serializer) | 
network-utilities | [![Build Status](https://travis-ci.com/yiisoft/network-utilities.svg?branch=master)](https://travis-ci.com/yiisoft/network-utilities) | [![Build Status](https://travis-ci.org/yiisoft/network-utilities.svg?branch=master)](https://travis-ci.org/yiisoft/network-utilities) | 
auth | [![Build Status](https://travis-ci.com/yiisoft/auth.svg?branch=master)](https://travis-ci.com/yiisoft/auth) | [![Build Status](https://travis-ci.org/yiisoft/auth.svg?branch=master)](https://travis-ci.org/yiisoft/auth) | 
cache | [![Build Status](https://travis-ci.com/yiisoft/cache.svg?branch=master)](https://travis-ci.com/yiisoft/cache) | [![Build Status](https://travis-ci.org/yiisoft/cache.svg?branch=master)](https://travis-ci.org/yiisoft/cache) | ✔
cache-apcu | [![Build Status](https://travis-ci.com/yiisoft/cache-apcu.svg?branch=master)](https://travis-ci.com/yiisoft/cache-apcu) | [![Build Status](https://travis-ci.org/yiisoft/cache-apcu.svg?branch=master)](https://travis-ci.org/yiisoft/cache-apcu) | 
cache-wincache | [![Build Status](https://travis-ci.com/yiisoft/cache-wincache.svg?branch=master)](https://travis-ci.com/yiisoft/cache-wincache) | [![Build Status](https://travis-ci.org/yiisoft/cache-wincache.svg?branch=master)](https://travis-ci.org/yiisoft/cache-wincache) | 
cache-file | [![Build Status](https://travis-ci.com/yiisoft/cache-file.svg?branch=master)](https://travis-ci.com/yiisoft/cache-file) | [![Build Status](https://travis-ci.org/yiisoft/cache-file.svg?branch=master)](https://travis-ci.org/yiisoft/cache-file) | 
cache-db | [![Build Status](https://travis-ci.com/yiisoft/cache-db.svg?branch=master)](https://travis-ci.com/yiisoft/cache-db) | [![Build Status](https://travis-ci.org/yiisoft/cache-db.svg?branch=master)](https://travis-ci.org/yiisoft/cache-db) | 
rbac | [![Build Status](https://travis-ci.com/yiisoft/rbac.svg?branch=master)](https://travis-ci.com/yiisoft/rbac) | [![Build Status](https://travis-ci.org/yiisoft/rbac.svg?branch=master)](https://travis-ci.org/yiisoft/rbac) | ✔
rbac-db | [![Build Status](https://travis-ci.com/yiisoft/rbac-db.svg?branch=master)](https://travis-ci.com/yiisoft/rbac-db) | [![Build Status](https://travis-ci.org/yiisoft/rbac-db.svg?branch=master)](https://travis-ci.org/yiisoft/rbac-db) | 
rbac-php | [![Build Status](https://travis-ci.com/yiisoft/rbac-php.svg?branch=master)](https://travis-ci.com/yiisoft/rbac-php) | [![Build Status](https://travis-ci.org/yiisoft/rbac-php.svg?branch=master)](https://travis-ci.org/yiisoft/rbac-php) | 
log | [![Build Status](https://travis-ci.com/yiisoft/log.svg?branch=master)](https://travis-ci.com/yiisoft/log) | [![Build Status](https://travis-ci.org/yiisoft/log.svg?branch=master)](https://travis-ci.org/yiisoft/log) | ✔
log-target-db | [![Build Status](https://travis-ci.com/yiisoft/log-target-db.svg?branch=master)](https://travis-ci.com/yiisoft/log-target-db) | [![Build Status](https://travis-ci.org/yiisoft/log-target-db.svg?branch=master)](https://travis-ci.org/yiisoft/log-target-db) | ✔
log-target-email | [![Build Status](https://travis-ci.com/yiisoft/log-target-email.svg?branch=master)](https://travis-ci.com/yiisoft/log-target-email) | [![Build Status](https://travis-ci.org/yiisoft/log-target-email.svg?branch=master)](https://travis-ci.org/yiisoft/log-target-email) | ✔
log-target-file | [![Build Status](https://travis-ci.com/yiisoft/log-target-file.svg?branch=master)](https://travis-ci.com/yiisoft/log-target-file) | [![Build Status](https://travis-ci.org/yiisoft/log-target-file.svg?branch=master)](https://travis-ci.org/yiisoft/log-target-file) | ✔
log-target-syslog | [![Build Status](https://travis-ci.com/yiisoft/log-target-syslog.svg?branch=master)](https://travis-ci.com/yiisoft/log-target-syslog) | [![Build Status](https://travis-ci.org/yiisoft/log-target-syslog.svg?branch=master)](https://travis-ci.org/yiisoft/log-target-syslog) | ✔
i18n | [![Build Status](https://travis-ci.com/yiisoft/i18n.svg?branch=master)](https://travis-ci.com/yiisoft/i18n) | [![Build Status](https://travis-ci.org/yiisoft/i18n.svg?branch=master)](https://travis-ci.org/yiisoft/i18n) | ✔
i18n-message-php | [![Build Status](https://travis-ci.com/yiisoft/i18n-message-php.svg?branch=master)](https://travis-ci.com/yiisoft/i18n-message-php) | [![Build Status](https://travis-ci.org/yiisoft/i18n-message-php.svg?branch=master)](https://travis-ci.org/yiisoft/i18n-message-php) | ✔
i18n-message-gettext | [![Build Status](https://travis-ci.com/yiisoft/i18n-message-gettext.svg?branch=master)](https://travis-ci.com/yiisoft/i18n-message-gettext) | [![Build Status](https://travis-ci.org/yiisoft/i18n-message-gettext.svg?branch=master)](https://travis-ci.org/yiisoft/i18n-message-gettext) | ✔
i18n-formatter-intl | [![Build Status](https://travis-ci.com/yiisoft/i18n-formatter-intl.svg?branch=master)](https://travis-ci.com/yiisoft/i18n-formatter-intl) | [![Build Status](https://travis-ci.org/yiisoft/i18n-formatter-intl.svg?branch=master)](https://travis-ci.org/yiisoft/i18n-formatter-intl) | ✔
yii-queue | [![Build Status](https://travis-ci.com/yiisoft/yii-queue.svg?branch=master)](https://travis-ci.com/yiisoft/yii-queue) | [![Build Status](https://travis-ci.org/yiisoft/yii-queue.svg?branch=master)](https://travis-ci.org/yiisoft/yii-queue) | ✔
yii-queue-interop | [![Build Status](https://travis-ci.com/yiisoft/yii-queue-interop.svg?branch=master)](https://travis-ci.com/yiisoft/yii-queue-interop) | [![Build Status](https://travis-ci.org/yiisoft/yii-queue-interop.svg?branch=master)](https://travis-ci.org/yiisoft/yii-queue-interop) | 
mutex | [![Build Status](https://travis-ci.com/yiisoft/mutex.svg?branch=master)](https://travis-ci.com/yiisoft/mutex) | [![Build Status](https://travis-ci.org/yiisoft/mutex.svg?branch=master)](https://travis-ci.org/yiisoft/mutex) | 
mutex-file | [![Build Status](https://travis-ci.com/yiisoft/mutex-file.svg?branch=master)](https://travis-ci.com/yiisoft/mutex-file) | [![Build Status](https://travis-ci.org/yiisoft/mutex-file.svg?branch=master)](https://travis-ci.org/yiisoft/mutex-file) | ✔
mutex-db-pgsql | [![Build Status](https://travis-ci.com/yiisoft/mutex-db-pgsql.svg?branch=master)](https://travis-ci.com/yiisoft/mutex-db-pgsql) | [![Build Status](https://travis-ci.org/yiisoft/mutex-db-pgsql.svg?branch=master)](https://travis-ci.org/yiisoft/mutex-db-pgsql) | ✔
mutex-db-oracle | [![Build Status](https://travis-ci.com/yiisoft/mutex-db-oracle.svg?branch=master)](https://travis-ci.com/yiisoft/mutex-db-oracle) | [![Build Status](https://travis-ci.org/yiisoft/mutex-db-oracle.svg?branch=master)](https://travis-ci.org/yiisoft/mutex-db-oracle) | ✔
mutex-db-mysql | [![Build Status](https://travis-ci.com/yiisoft/mutex-db-mysql.svg?branch=master)](https://travis-ci.com/yiisoft/mutex-db-mysql) | [![Build Status](https://travis-ci.org/yiisoft/mutex-db-mysql.svg?branch=master)](https://travis-ci.org/yiisoft/mutex-db-mysql) | ✔
mailer | [![Build Status](https://travis-ci.com/yiisoft/mailer.svg?branch=master)](https://travis-ci.com/yiisoft/mailer) | [![Build Status](https://travis-ci.org/yiisoft/mailer.svg?branch=master)](https://travis-ci.org/yiisoft/mailer) | ✔
mailer-swiftmailer | [![Build Status](https://travis-ci.com/yiisoft/mailer-swiftmailer.svg?branch=master)](https://travis-ci.com/yiisoft/mailer-swiftmailer) | [![Build Status](https://travis-ci.org/yiisoft/mailer-swiftmailer.svg?branch=master)](https://travis-ci.org/yiisoft/mailer-swiftmailer) | ✔
arrays | [![Build Status](https://travis-ci.com/yiisoft/arrays.svg?branch=master)](https://travis-ci.com/yiisoft/arrays) | [![Build Status](https://travis-ci.org/yiisoft/arrays.svg?branch=master)](https://travis-ci.org/yiisoft/arrays) | ✔
strings | [![Build Status](https://travis-ci.com/yiisoft/strings.svg?branch=master)](https://travis-ci.com/yiisoft/strings) | [![Build Status](https://travis-ci.org/yiisoft/strings.svg?branch=master)](https://travis-ci.org/yiisoft/strings) | ✔
files | [![Build Status](https://travis-ci.com/yiisoft/files.svg?branch=master)](https://travis-ci.com/yiisoft/files) | [![Build Status](https://travis-ci.org/yiisoft/files.svg?branch=master)](https://travis-ci.org/yiisoft/files) | 
var-dumper | [![Build Status](https://travis-ci.com/yiisoft/var-dumper.svg?branch=master)](https://travis-ci.com/yiisoft/var-dumper) | [![Build Status](https://travis-ci.org/yiisoft/var-dumper.svg?branch=master)](https://travis-ci.org/yiisoft/var-dumper) | 
html | [![Build Status](https://travis-ci.com/yiisoft/html.svg?branch=master)](https://travis-ci.com/yiisoft/html) | [![Build Status](https://travis-ci.org/yiisoft/html.svg?branch=master)](https://travis-ci.org/yiisoft/html) | 
json | [![Build Status](https://travis-ci.com/yiisoft/json.svg?branch=master)](https://travis-ci.com/yiisoft/json) | [![Build Status](https://travis-ci.org/yiisoft/json.svg?branch=master)](https://travis-ci.org/yiisoft/json) | 
yii-console | [![Build Status](https://travis-ci.com/yiisoft/yii-console.svg?branch=master)](https://travis-ci.com/yiisoft/yii-console) | [![Build Status](https://travis-ci.org/yiisoft/yii-console.svg?branch=master)](https://travis-ci.org/yiisoft/yii-console) | ✔
yii-rest | [![Build Status](https://travis-ci.com/yiisoft/yii-rest.svg?branch=master)](https://travis-ci.com/yiisoft/yii-rest) | [![Build Status](https://travis-ci.org/yiisoft/yii-rest.svg?branch=master)](https://travis-ci.org/yiisoft/yii-rest) | ✔
db | [![Build Status](https://travis-ci.com/yiisoft/db.svg?branch=master)](https://travis-ci.com/yiisoft/db) | [![Build Status](https://travis-ci.org/yiisoft/db.svg?branch=master)](https://travis-ci.org/yiisoft/db) | ✔
db-mysql | [![Build Status](https://travis-ci.com/yiisoft/db-mysql.svg?branch=master)](https://travis-ci.com/yiisoft/db-mysql) | [![Build Status](https://travis-ci.org/yiisoft/db-mysql.svg?branch=master)](https://travis-ci.org/yiisoft/db-mysql) | ✔
db-pgsql | [![Build Status](https://travis-ci.com/yiisoft/db-pgsql.svg?branch=master)](https://travis-ci.com/yiisoft/db-pgsql) | [![Build Status](https://travis-ci.org/yiisoft/db-pgsql.svg?branch=master)](https://travis-ci.org/yiisoft/db-pgsql) | ✔
db-sqlite | [![Build Status](https://travis-ci.com/yiisoft/db-sqlite.svg?branch=master)](https://travis-ci.com/yiisoft/db-sqlite) | [![Build Status](https://travis-ci.org/yiisoft/db-sqlite.svg?branch=master)](https://travis-ci.org/yiisoft/db-sqlite) | ✔
db-mssql | [![Build Status](https://travis-ci.com/yiisoft/db-mssql.svg?branch=master)](https://travis-ci.com/yiisoft/db-mssql) | [![Build Status](https://travis-ci.org/yiisoft/db-mssql.svg?branch=master)](https://travis-ci.org/yiisoft/db-mssql) | 
db-oracle | [![Build Status](https://travis-ci.com/yiisoft/db-oracle.svg?branch=master)](https://travis-ci.com/yiisoft/db-oracle) | [![Build Status](https://travis-ci.org/yiisoft/db-oracle.svg?branch=master)](https://travis-ci.org/yiisoft/db-oracle) | 
db-mongodb | [![Build Status](https://travis-ci.com/yiisoft/db-mongodb.svg?branch=master)](https://travis-ci.com/yiisoft/db-mongodb) | [![Build Status](https://travis-ci.org/yiisoft/db-mongodb.svg?branch=master)](https://travis-ci.org/yiisoft/db-mongodb) | ✔
active-record | [![Build Status](https://travis-ci.com/yiisoft/active-record.svg?branch=master)](https://travis-ci.com/yiisoft/active-record) | [![Build Status](https://travis-ci.org/yiisoft/active-record.svg?branch=master)](https://travis-ci.org/yiisoft/active-record) | ✔
yii-cycle | [![Build Status](https://travis-ci.com/yiisoft/yii-cycle.svg?branch=master)](https://travis-ci.com/yiisoft/yii-cycle) | [![Build Status](https://travis-ci.org/yiisoft/yii-cycle.svg?branch=master)](https://travis-ci.org/yiisoft/yii-cycle) | 
router | [![Build Status](https://travis-ci.com/yiisoft/router.svg?branch=master)](https://travis-ci.com/yiisoft/router) | [![Build Status](https://travis-ci.org/yiisoft/router.svg?branch=master)](https://travis-ci.org/yiisoft/router) | 
router-fastroute | [![Build Status](https://travis-ci.com/yiisoft/router-fastroute.svg?branch=master)](https://travis-ci.com/yiisoft/router-fastroute) | [![Build Status](https://travis-ci.org/yiisoft/router-fastroute.svg?branch=master)](https://travis-ci.org/yiisoft/router-fastroute) | 
yii-web | [![Build Status](https://travis-ci.com/yiisoft/yii-web.svg?branch=master)](https://travis-ci.com/yiisoft/yii-web) | [![Build Status](https://travis-ci.org/yiisoft/yii-web.svg?branch=master)](https://travis-ci.org/yiisoft/yii-web) | ✔
view | [![Build Status](https://travis-ci.com/yiisoft/view.svg?branch=master)](https://travis-ci.com/yiisoft/view) | [![Build Status](https://travis-ci.org/yiisoft/view.svg?branch=master)](https://travis-ci.org/yiisoft/view) | ✔
yii-jquery | [![Build Status](https://travis-ci.com/yiisoft/yii-jquery.svg?branch=master)](https://travis-ci.com/yiisoft/yii-jquery) | [![Build Status](https://travis-ci.org/yiisoft/yii-jquery.svg?branch=master)](https://travis-ci.org/yiisoft/yii-jquery) | ✔
yii-masked-input | [![Build Status](https://travis-ci.com/yiisoft/yii-masked-input.svg?branch=master)](https://travis-ci.com/yiisoft/yii-masked-input) | [![Build Status](https://travis-ci.org/yiisoft/yii-masked-input.svg?branch=master)](https://travis-ci.org/yiisoft/yii-masked-input) | ✔
yii-dataview | [![Build Status](https://travis-ci.com/yiisoft/yii-dataview.svg?branch=master)](https://travis-ci.com/yiisoft/yii-dataview) | [![Build Status](https://travis-ci.org/yiisoft/yii-dataview.svg?branch=master)](https://travis-ci.org/yiisoft/yii-dataview) | 
yii-debug | [![Build Status](https://travis-ci.com/yiisoft/yii-debug.svg?branch=master)](https://travis-ci.com/yiisoft/yii-debug) | [![Build Status](https://travis-ci.org/yiisoft/yii-debug.svg?branch=master)](https://travis-ci.org/yiisoft/yii-debug) | ✔
yii-gii | [![Build Status](https://travis-ci.com/yiisoft/yii-gii.svg?branch=master)](https://travis-ci.com/yiisoft/yii-gii) | [![Build Status](https://travis-ci.org/yiisoft/yii-gii.svg?branch=master)](https://travis-ci.org/yiisoft/yii-gii) | ✔
yii-bootstrap4 | [![Build Status](https://travis-ci.com/yiisoft/yii-bootstrap4.svg?branch=master)](https://travis-ci.com/yiisoft/yii-bootstrap4) | [![Build Status](https://travis-ci.org/yiisoft/yii-bootstrap4.svg?branch=master)](https://travis-ci.org/yiisoft/yii-bootstrap4) | ✔
yii-captcha | [![Build Status](https://travis-ci.com/yiisoft/yii-captcha.svg?branch=master)](https://travis-ci.com/yiisoft/yii-captcha) | [![Build Status](https://travis-ci.org/yiisoft/yii-captcha.svg?branch=master)](https://travis-ci.org/yiisoft/yii-captcha) | ✔
yii-auth-client | [![Build Status](https://travis-ci.com/yiisoft/yii-auth-client.svg?branch=master)](https://travis-ci.com/yiisoft/yii-auth-client) | [![Build Status](https://travis-ci.org/yiisoft/yii-auth-client.svg?branch=master)](https://travis-ci.org/yiisoft/yii-auth-client) | ✔
yii-base-api | [![Build Status](https://travis-ci.com/yiisoft/yii-base-api.svg?branch=master)](https://travis-ci.com/yiisoft/yii-base-api) | [![Build Status](https://travis-ci.org/yiisoft/yii-base-api.svg?branch=master)](https://travis-ci.org/yiisoft/yii-base-api) | ✔
yii-base-web | [![Build Status](https://travis-ci.com/yiisoft/yii-base-web.svg?branch=master)](https://travis-ci.com/yiisoft/yii-base-web) | [![Build Status](https://travis-ci.org/yiisoft/yii-base-web.svg?branch=master)](https://travis-ci.org/yiisoft/yii-base-web) | ✔
yii-project-template | [![Build Status](https://travis-ci.com/yiisoft/yii-project-template.svg?branch=master)](https://travis-ci.com/yiisoft/yii-project-template) | [![Build Status](https://travis-ci.org/yiisoft/yii-project-template.svg?branch=master)](https://travis-ci.org/yiisoft/yii-project-template) | ✔
yii-demo | [![Build Status](https://travis-ci.com/yiisoft/yii-demo.svg?branch=master)](https://travis-ci.com/yiisoft/yii-demo) | [![Build Status](https://travis-ci.org/yiisoft/yii-demo.svg?branch=master)](https://travis-ci.org/yiisoft/yii-demo) | 
yii-docker | [![Build Status](https://travis-ci.com/yiisoft/yii-docker.svg?branch=master)](https://travis-ci.com/yiisoft/yii-docker) | [![Build Status](https://travis-ci.org/yiisoft/yii-docker.svg?branch=master)](https://travis-ci.org/yiisoft/yii-docker) | 
validator | [![Build Status](https://travis-ci.com/yiisoft/validator.svg?branch=master)](https://travis-ci.com/yiisoft/validator) | [![Build Status](https://travis-ci.org/yiisoft/validator.svg?branch=master)](https://travis-ci.org/yiisoft/validator) | ✔
friendly-exception | [![Build Status](https://travis-ci.com/yiisoft/friendly-exception.svg?branch=master)](https://travis-ci.com/yiisoft/friendly-exception) | [![Build Status](https://travis-ci.org/yiisoft/friendly-exception.svg?branch=master)](https://travis-ci.org/yiisoft/friendly-exception) | 
template | [![Build Status](https://travis-ci.com/yiisoft/template.svg?branch=master)](https://travis-ci.com/yiisoft/template) | [![Build Status](https://travis-ci.org/yiisoft/template.svg?branch=master)](https://travis-ci.org/yiisoft/template) | 
requirements | [![Build Status](https://travis-ci.com/yiisoft/requirements.svg?branch=master)](https://travis-ci.com/yiisoft/requirements) | [![Build Status](https://travis-ci.org/yiisoft/requirements.svg?branch=master)](https://travis-ci.org/yiisoft/requirements) | 

</details>

**Comment by samdark** [comment] 2019-12-06 14:33
Arrgh. That's a mess with .com and .org :(

**Comment by rugabarbo** [comment] 2019-12-06 14:47
Keep calm :) 

I have found a reason. For travis-ci.**COM**, we need to get the keys differently during Slack token encryption: https://docs.travis-ci.com/user/encryption-keys/#obtaining-the-public-keys 

I'll fix it.

**Comment by samdark** [comment] 2019-12-06 14:55
I can migrate everything to .com so it will be consistent.

**Comment by rugabarbo** [comment] 2019-12-06 15:03
I can write a small console command for automatic migration. Travis API provides the ability to start migration: https://developer.travis-ci.com/resource/repository#migrate

How difficult is it to migrate everything manually? Is it possible to migrate everything with one click?
If it’s difficult to migrate manually, it will only take me 10 minutes to write a command and start the migration using Travis API.

**Comment by samdark** [comment] 2019-12-06 15:18
> How difficult is it to migrate everything manually? Is it possible to migrate everything with one click?

Yes.

**Comment by samdark** [comment] 2019-12-06 16:01
Migrated/

**Comment by rugabarbo** [comment] 2019-12-06 16:15
@samdark 

1. Merge #59 
2. [Update](https://github.com/yiisoft/yii-dev-tool/#upgrade) `yii-dev-tool` locally 
3. Generate and copy **Travis API** token for travis-ci.**COM**
4. Place the token in file `yii-dev-tool/config/travis/api.local.php` (use `api.local.php.example` as example)
5. Prepare the repositories for pushing new things (use updated clean `master` branch)
6. Run `./yii-dev travis/update-slack-config --verbose`
7. Push the changes to the repositories

Pay attention, now in steps 3 and 4 you need tokens specifically for **Travis API**, not for Slack. **Leave Slack token the same as it was!**

**Comment by samdark** [comment] 2019-12-06 16:58
All done but it seems there are problems:

- .org builds are still triggered. There are stale webhooks from very old travis-ci.org in each repository in yiisoft. `https://notify.travis-ci.org/`
- .com builds seems to be triggered properly but aren't ending up in Slack

**Comment by samdark** [comment] 2019-12-06 20:21
I'll handle .org issue separately. Slack works well. Thank you again for preparing all that.

**Closed by samdark** 2019-12-06 20:21 UTC

**Comment by rugabarbo** [comment] 2019-12-06 21:34
Yes, now everything seems to be working fine.
You are welcome! ;)
